name: Build Mossbunker App

on: workflow_dispatch

env:
  FILENAME: Mossbunker V${{vars.VERSION}}.apk

jobs:
  build_for_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install Flutter
        uses: subosito/flutter-action@v2.12.0
      - name: Install dependencies & build APK
        run: \
        pushd mossbunker/ \
        flutter pub get \
        flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.FILENAME}}
          path: mossbunker/build/app/outputs/flutter-apk/app-release.apk